[package]
name = "move-origin"
version = "0.0.0"

[dependencies]
MoveStdlib = { git = "/Users/qinjianquan/Career/move", subdir = "language/move-stdlib", rev = "main" }
MoveNursery = { git = "/Users/qinjianquan/Career/move", subdir = "language/move-stdlib/nursery", rev = "main" }

[addresses]
std =  "0x1"



